services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: demodb
    environment:
      MSSQL_SA_PASSWORD: "Pwd@321"
      ACCEPT_EULA: "Y"
      MSSSQL_PID: "Developer"
    ports:
      - "1455:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - miniproject

  simpleinventory:
    build: 
      context: ../MiniProject
      dockerfile: SimpleInventory/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - miniproject

  dbtool:
    image: mcr.microsoft.com/mssql-tools
    networks:
      - miniproject

volumes:
  mssql-data:

networks:
  miniproject: